name: Pull Request
on:
  workflow_call:
  pull_request:
    types: [opened, reopened, edited]
jobs:
  release:
    uses: modbus2mqtt/specification/.github/workflows/pull.yml@main
    permissions:
      contents: write
